### ISSUE TITLE
Incorporate ability to interpret two dates of imagery at the same time

### ISSUE THREAD

**Issue by rhamilton03** [openforis/collect-earth-online#140] opened 2018-07-02 17:44 UTC
In the projects I work on, it is critical to be able to interpret two dates of imagery at the same time. This is because we use dot level information within the plots and it is essential to be able to compare and interpret two dates of imagery simultaneously in order to visually compensate for any image shift that exists between the two dates to ensure that what is being interpreted is at the same location in both images.

**Comment by sirmspencer** [comment] 2020-11-10 18:53
This is now a duplicate of #396

**Closed by sirmspencer** 2020-11-10 18:53 UTC
Labels: Feature Request, High Priority
