### ISSUE TITLE
Track time spent filling out collection on each plot

### ISSUE THREAD

**Issue by KMarkert** [openforis/collect-earth-online#157] opened 2018-11-20 17:50 UTC
Would it be possible to add a 'begin' and 'end' time stamp to output file, to track when a user started classifying a plot, and when they finished the plot? 

This should be some timer on the backend that the user doesn't have to see.

**Comment by snasaio** [comment] 2018-12-07 22:37
Functionality added to postres server in #160

**Comment by snasaio** [comment] 2018-12-07 22:41
This appears to be a duplicate of #152

**Comment by sirmspencer** [comment] 2019-02-03 17:49
This functionality has been merged into master

**Closed by sirmspencer** 2019-02-03 17:49 UTC
Labels: enhancement
