### ISSUE TITLE
Record Imagery Date

### ISSUE THREAD

**Issue by kdyson** [openforis/collect-earth-online#1016] opened 2021-01-15 20:30 UTC
Record imagery date associated with imagery when survey questions are answered. For imagery sources (e.g. Planet NICFI) where dates are available, record both imagery source and date. For those without dates, record only imagery source. I think this is an expansion of the functionality in SecureWatch.

As far as I understand, the imagery is only recorded once per sample. So they would need to do two projects to record multiple dates. This may also be something to think about in the future, although I know the database changes might be significant. 

Request from Ecuador team among others. This feature is included in E.7 funding if awarded.

**Comment by sirmspencer** [comment] 2021-01-15 22:41
This is a duplicate of #428

**Closed by sirmspencer** 2021-01-15 22:41 UTC
Labels: Feature Request
