### ISSUE TITLE
Suggestion: Enable simultaneous interpretation of two dates of imagery

### ISSUE THREAD

**Issue by rhamilton03** [openforis/collect-earth-online#98] opened 2017-09-07 16:33 UTC
For our work in Costa Rica, it would be helpful if CEO could launch two windows with different dates of imagery for the same plot to enable simultaneous interpretation of the two dates. This makes it easier to detect and account for potential image shift between dates that could erroneously cause change; it also would allow the user to document cause of change when it occurs.

**Comment by snasaio** [comment] 2018-12-26 03:52
Duplicate of #140

**Closed by snasaio** 2018-12-26 03:52 UTC
