### ISSUE TITLE
high resolution imagery in Geo-Dash

### ISSUE THREAD

**Issue by kdyson** [openforis/collect-earth-online#685] opened 2020-09-04 19:40 UTC
Feature request: Users in Costa Rica would like the ability to view high resolution data (e.g. Planet, WMS orthophotos) for two different specific dates side by side.

Currently they use the imagery pulled up in a different window, which lacks the pan and zoom synchronization.

**Comment by sirmspencer** [comment] 2020-09-18 21:06
I have a feeling that the geodash wont be sufficient.  It lacks the controls for the planet and secure watch layers.

**Comment by sirmspencer** [comment] 2020-09-18 21:16
This is a duplicate of #140

**Closed by sirmspencer** 2020-09-18 21:16 UTC
