### ISSUE TITLE
Suggestion: Allow interpretation of two dates of imagery at the same time

### ISSUE THREAD

**Issue by rhamilton03** [openforis/collect-earth-online#81] opened 2017-08-10 16:02 UTC
When a user is interested in interpreting more than one date of imagery, it would be helpful if CEO could allow two windows to appear for a given plot with different dates of imagery so that the user can interpret the two dates at the same time. Ideally, the user would be able to quickly copy attributes from points that have not changed for one year to the next year to make the process more efficient.

**Comment by snasaio** [comment] 2018-12-26 03:54
Duplicate of #140

**Closed by snasaio** 2018-12-26 03:54 UTC
