### ISSUE TITLE
For multi-attribute projects, allow collapsing of attributes not being used at the time

### ISSUE THREAD

**Issue by rhamilton03** [openforis/collect-earth-online#133] opened 2018-05-08 22:46 UTC
For projects we are working on in Costa Rica, we need to be able to see and interpret two dates of imagery at the same time (mainly to ensure that the dots in the plots are hitting the same thing in case of image shift between the two dates and to visually compensate if present). Right now, there appears to be no easy way to do this in CEO. Since there is a great need to interpret information for multiple dates, I'd encourage development of better ways to do this. 

In our case, one possible work-around is to enter land use attributes for time 1, land cover attributes for time 1, land use attributes for time 2, and land cover attributes for time 2. We have quite a few classes for each one. Because of this, it becomes difficult to have to scroll way down the list to get to the attributes of interest. One suggestion is to add functionality that would allow us to collapse the attribute sets that we are not using at the time.

**Comment by snasaio** [comment] 2018-12-26 04:19
For individual attributes the UI on the current release allows you to hide and show each question and answer group.  As far as being able to interpret two dates of imagery at the same time, this is a duplicate of #140

**Closed by snasaio** 2018-12-26 04:19 UTC
